apiVersion: v1
kind: Service
metadata:
  name: timothy-portfolio
spec:
  type: NodePort
  ports:
    - port: 31000
      nodePort: 31000
      targetPort: http
      protocol: TCP
  selector:
    app: subscriptions
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "timothy-portfolio"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "subscriptions"
        env: prod
    spec:
      containers:
        - name: subscriptions
          image: "timothylock/timothy-portfolio:latest"
          ports:
            - containerPort: 80
              name: http