apiVersion: v1
kind: Service
metadata:
  name: 8thmarkham
spec:
  type: NodePort
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: http
      protocol: TCP
  selector:
    app: 8thmarkham
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "8thmarkham"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "8thmarkham"
        env: prod
    spec:
      containers:
        - name: 8thmarkham
          image: "timothylock/8thmarkham:latest"
          ports:
            - containerPort: 80
              name: http
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password