apiVersion: v1
kind: Service
metadata:
  name: timothy-blog
spec:
  type: NodePort
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: http
      protocol: TCP
  selector:
    app: timothy-blog
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "timothy-blog"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "timothy-blog"
        env: prod
    spec:
      containers:
        - name: timothy-blog
          image: "timothylock/timothy-blog:latest"
          ports:
            - containerPort: 80
              name: http
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password