version: '2'

services:
  timothy-blog:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: wordpress:latest
     ports:
       - "9000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASS}
       WORDPRESS_DB_NAME: timothy-blog
       VIRTUAL_HOST: blog.timothylock.ca
     volumes:
       - ../src/timothy-blog/wp-content:/var/www/html/wp-content/
     network_mode: "bridge"

  timothys-stuff:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: wordpress:latest
     ports:
       - "9001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASS}
       WORDPRESS_DB_NAME: timothysstuffPRIVATE
       VIRTUAL_HOST: timothys-stuff.timothylock.ca
     volumes:
       - /mnt/storage/privateblog/wp-content:/var/www/html/wp-content/
       - ../src/timothys-stuff/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     network_mode: "bridge"

  mysql:
     image: mysql:5.7
     ports:
       - "9010:3306"
     volumes:
       - mysqldata:/var/lib/mysql
     restart: always
     environment:
       WORDPRESS_DB_USER: root
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
       MYSQL_USER: user
       MYSQL_PASSWORD: ${MYSQL_USER_PASS}
     network_mode: "bridge"

#  phpmyadmin:
#     depends_on:
#       - mysql
#     image: phpmyadmin/phpmyadmin:latest
#     ports:
#       - "9011:80"
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       PMA_HOST: mysql:9010
#       VIRTUAL_HOST: phpmyadmin.timothylock.ca
#     network_mode: "bridge"

  timothy-portfolio:
     image: richarvey/nginx-php-fpm:latest
     ports:
       - "9020:80"
     restart: always
     environment:
       VIRTUAL_HOST: www.timothylock.ca,timothylock.ca
     volumes:
       - ../src/timothy-portfolio/src:/var/www/html
       - ../src/timothy-portfolio/config/nginx.conf /etc/nginx/nginx.conf
     network_mode: "bridge"

  markham8-blog:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: wordpress:latest
     ports:
       - "9030:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASS}
       WORDPRESS_DB_NAME: 8thmarkham-blog
       VIRTUAL_HOST: 8thmarkham.com
     volumes:
       - ../src/markham8-blog/wp-content:/var/www/html/wp-content/
       - ../src/markham8-blog/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     network_mode: "bridge"

  markham8-leaders:
     image: timothylock/markham8-leaders:latest
     ports:
       - "9031:80"
     restart: always
     environment:
       VIRTUAL_HOST: leaders.8thmarkham.com
     volumes:
       - ../src/markham8-leaders/files:/var/www/html/files/
     network_mode: "bridge"

  csc309-tb-exchange:
     depends_on:
       - csc309-mongodb
     links:
       - csc309-mongodb:csc309-mongodb
     image: timothylock/csc309-textbook-exchange:latest
     ports:
       - "9040:80"
     restart: always
     environment:
       VIRTUAL_HOST: uoftextbookexchange.timothylock.ca
     network_mode: "bridge"

  csc309-mongodb:
     image: mongo:latest
     environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
     volumes:
       - ../src/csc309-mongodb/data:/data
     ports:
       - "27017:27017"
     command: mongod --smallfiles --logpath=/dev/null
     network_mode: "bridge"

  pi-monitor:
     image: timothylock/tim-pi-monitor-demo:latest
     ports:
       - "9050:8880"
     restart: always
     environment:
       VIRTUAL_HOST: homemonitordemo.timothylock.ca
     network_mode: "bridge"

#  REASON: Hosted on Github Pages now
#
#  lock-family:
#     image: richarvey/nginx-php-fpm:latest
#     ports:
#       - "9060:80"
#     restart: always
#     environment:
#       VIRTUAL_HOST: lockfamily.timothylock.ca
#     volumes:
#       - ../src/lock-family/src:/var/www/html
#       - ../src/lock-family/config/nginx.conf:/etc/nginx/nginx.conf
#     network_mode: "bridge"

  comp-with-tim:
     image: ianneub/redirect
     ports:
       - "9070:80"
     restart: always
     environment:
       VIRTUAL_HOST: computerswithtim.ml
       REDIRECT: https://sites.google.com/logicfusion.ca/tims-class-site
     network_mode: "bridge"

#  security:
#     image: ianneub/redirect
#     ports:
#       - "9071:80"
#     restart: always
#     environment:
#       VIRTUAL_HOST: security.timothylock.ca
#       REDIRECT: http://10.88.111.12:8123
#     network_mode: "bridge"

  nextcloud:
    image: nextcloud:latest
    ports:
      - "9080:80"
    environment:
      VIRTUAL_HOST: data.timothylock.ca
    links:
      - mysql
    volumes:
      - /mnt/storage/nextcloud:/var/www/html/
    restart: always
    network_mode: "bridge"

  mysql-backup:
    image: dsteinkopf/backup-all-mysql:latest
    environment:
      - BACKUP_INTERVAL=86400
      - BACKUP_FIRSTDELAY=5
    links:
      - mysql
    restart: always
    volumes:
      - /mnt/storage/dbdumps/mainmysql:/var/dbdumps
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    network_mode: "bridge"

  home-assistant:
    image: homeassistant/home-assistant
    ports:
      - "9090:9999"
    environment:
      VIRTUAL_HOST: home.timothylock.ca
    restart: always
    volumes:
      - ../src/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOME_ASSISTANT_API_PASSWORD=${HOME_ASSISTANT_API_PASSWORD}
      - HOME_ASSISTANT_DB_URL=${HOME_ASSISTANT_DB_URL}
    network_mode: "host"

  screenboard:
     image: ianneub/redirect
     ports:
       - "9090:80"
     restart: always
     environment:
       VIRTUAL_HOST: screenboard.timothylock.ca
       REDIRECT: http://preview.risevision.com/?type=presentation&id=5b3ed960-d778-420d-87da-c73ba8e7d76d
     network_mode: "bridge"

volumes:
    mysqldata:
