version: '2'

services:
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/timothy/.docker/config.json:/config.json

  urlshortener:
    image: yourls
    restart: always
    links: 
      - mysql:mysql
    ports:
      - 10060:80
    environment:
      YOURLS_DB_PASS: ${MYSQL_ROOT_PASS}
      YOURLS_DB_HOST: mysql:3306
      YOURLS_DB_USER: root
      YOURLS_SITE: https://r.timothylock.ca
      YOURLS_USER: timothy
      YOURLS_PASS: password
      VIRTUAL_HOST: r.timothylock.ca
    network_mode: "bridge"

  php-sandbox:
     image: richarvey/nginx-php-fpm
     restart: always
     volumes:
       - /home/timothy/sandbox-php:/var/www/html
     ports:
       - "10040:80"
     environment:
       VIRTUAL_HOST: php-sandbox.timothylock.ca
         
  timothys-stuff:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: wordpress:latest
     ports:
       - "9001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASS}
       WORDPRESS_DB_NAME: timothysstuffPRIVATE
       VIRTUAL_HOST: timothys-stuff.timothylock.ca
     volumes:
       - /mnt/storage/privateblog/wp-content:/var/www/html/wp-content/
       - ../src/timothys-stuff/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     network_mode: "bridge"

  mysql:
     image: mysql:5.7
     ports:
       - "9010:3306"
     volumes:
       - mysqldata:/var/lib/mysql
     restart: always
     environment:
       WORDPRESS_DB_USER: root
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
       MYSQL_USER: user
       MYSQL_PASSWORD: ${MYSQL_USER_PASS}
     network_mode: "bridge"

  markham8-blog:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: wordpress:latest
     ports:
       - "9030:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASS}
       WORDPRESS_DB_NAME: 8thmarkham-blog
       VIRTUAL_HOST: 8thmarkham.com
     volumes:
       - ../src/markham8-blog/wp-content:/var/www/html/wp-content/
       - ../src/markham8-blog/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     network_mode: "bridge"

  markham8-leaders:
     image: timothylock/markham8-leaders:latest
     ports:
       - "9031:80"
     restart: always
     environment:
       VIRTUAL_HOST: leaders.8thmarkham.com
     volumes:
       - ../src/markham8-leaders/files:/var/www/html/files/
     network_mode: "bridge"

  csc309-tb-exchange:
     depends_on:
       - csc309-mongodb
     links:
       - csc309-mongodb:csc309-mongodb
     image: timothylock/csc309-textbook-exchange:latest
     ports:
       - "9040:80"
     restart: always
     environment:
       VIRTUAL_HOST: uoftextbookexchange.timothylock.ca
     network_mode: "bridge"

  csc309-mongodb:
     image: mongo:latest
     environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
     volumes:
       - ../src/csc309-mongodb/data:/data
     ports:
       - "27017:27017"
     command: mongod --smallfiles --logpath=/dev/null
     network_mode: "bridge"

  pi-monitor:
     image: timothylock/tim-pi-monitor-demo:latest
     ports:
       - "9050:8880"
     restart: always
     environment:
       VIRTUAL_HOST: homemonitordemo.timothylock.ca
     network_mode: "bridge"

  nextcloud:
    image: nextcloud:latest
    ports:
      - "9080:80"
    environment:
      VIRTUAL_HOST: data.timothylock.ca
    links:
      - mysql
    volumes:
      - /mnt/storage/nextcloud:/var/www/html/
    restart: always
    network_mode: "bridge"

  mysql-backup:
    image: dsteinkopf/backup-all-mysql:latest
    environment:
      - BACKUP_INTERVAL=86400
      - BACKUP_FIRSTDELAY=5
    links:
      - mysql
    restart: always
    volumes:
      - /mnt/storage/dbdumps/mainmysql:/var/dbdumps
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    network_mode: "bridge"

  home-assistant:
    image: homeassistant/home-assistant
    ports:
      - "9090:9999"
    environment:
      VIRTUAL_HOST: home.timothylock.ca
    restart: always
    volumes:
      - ../src/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOME_ASSISTANT_API_PASSWORD=${HOME_ASSISTANT_API_PASSWORD}
      - HOME_ASSISTANT_DB_URL=${HOME_ASSISTANT_DB_URL}
    network_mode: "host"

  calendar:
    image: ianneub/redirect
    ports:
      - "10010:80"
    restart: always
    environment:
      VIRTUAL_HOST: calendar.timothylock.ca
      REDIRECT: https://calendar.google.com/calendar/embed?src=lock.k.timothy%40gmail.com&ctz=America%2FToronto&mode=WEEK
    network_mode: "bridge"

  inventory-personal:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: timothylock/inventory-management:latest
     ports:
       - "10020:9090"
     restart: always
     environment:
       VIRTUAL_HOST: inventory.timothylock.ca
       DB_URL: mysql:3306
       DB_USER: root
       DB_PASS: ${MYSQL_ROOT_PASS}
       DB_NAME: inventory
       UPC_URL: https://www.buycott.com/api/v3/products/lookup
       UPC_TOKEN: ${UPC_LOOKUP_TOKEN}
       FRONTEND_PATH: /frontend
       EMAIL_SMTP_SERV: ${ZOHO_SERV}
       EMAIL_SMTP_PORT: ${ZOHO_PORT}
       EMAIL_USERNAME: ${ZOHO_USR}
       EMAIL_PASSWORD: ${ZOHO_PASS}
       EMAIL_FROM_ADDR: ${ZOHO_FROM_ADDR}
     network_mode: "bridge"

  inventory-demo:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: timothylock/inventory-management:latest
     ports:
       - "10021:9090"
     restart: always
     environment:
       VIRTUAL_HOST: inventorydemo.timothylock.ca
       DB_URL: mysql:3306
       DB_USER: root
       DB_PASS: ${MYSQL_ROOT_PASS}
       DB_NAME: inventorydemo
       UPC_URL: https://www.buycott.com/api/v3/products/lookup
       UPC_TOKEN: ${UPC_LOOKUP_TOKEN}
       FRONTEND_PATH: /frontend
       EMAIL_SMTP_SERV: none
       EMAIL_SMTP_PORT: none
       EMAIL_USERNAME: none
       EMAIL_PASSWORD: none
       EMAIL_FROM_ADDR: none
     network_mode: "bridge"

  inventory-utat:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: timothylock/inventory-management:latest
     ports:
       - "10022:9090"
     restart: always
     environment:
       VIRTUAL_HOST: aeroinventory.utat.ca,aeroinventory.timothylock.ca
       DB_URL: mysql:3306
       DB_USER: root
       DB_PASS: ${MYSQL_ROOT_PASS}
       DB_NAME: inventoryutat
       UPC_URL: https://www.buycott.com/api/v3/products/lookup
       UPC_TOKEN: ${UPC_LOOKUP_TOKEN}
       FRONTEND_PATH: /frontend
       EMAIL_SMTP_SERV: ${ZOHO_SERV}
       EMAIL_SMTP_PORT: ${ZOHO_PORT}
       EMAIL_USERNAME: ${ZOHO_USR}
       EMAIL_PASSWORD: ${ZOHO_PASS}
       EMAIL_FROM_ADDR: ${ZOHO_FROM_ADDR}
     network_mode: "bridge"

  home-assistant-redirect:
      image: ianneub/redirect
      ports:
        - "10030:80"
      restart: always
      environment:
        VIRTUAL_HOST: home.timothylock.ca
        REDIRECT: http://vpn.timothylock.ca:8080
      network_mode: "bridge"

  twilio-buzzer-connector:
    image: timothylock/twilio-buzzer-connector
    ports:
      - "10050:8080"
    restart: always
    environment:
      VIRTUAL_HOST: buzzer.timothylock.ca
      WHITELISTED_NUMBERS: ${BUZZER_WHITELISTED_NUMBERS}
      BUZZCODE: ${BUZZCODE}
      MINUTES: 30
    network_mode: "bridge"

volumes:
    mysqldata:
