version: '3.3'

services:
  nginx-proxy:
     image: timothylock/nginx-proxy
     container_name: nginx-proxy
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro

  timothy-blog:
     depends_on:
       - mysql
     image: wordpress:latest
     ports:
       - "9000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_DB_NAME: timothy-blog
     volumes:
       - ../src/timothy-blog/wp-content:/var/www/html/wp-content/

  mysql:
     image: mysql:5.7
     ports:
       - "9010:3306"
     volumes:
       - mysqldata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_USER: user
       MYSQL_PASSWORD: password

  phpmyadmin:
     depends_on:
       - mysql
     image: phpmyadmin/phpmyadmin:latest
     ports:
       - "9011:80"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       PMA_HOST: mysql:3306

  timothy-portfolio:
     image: timothylock/timothy-portfolio:latest
     ports:
       - "9020:80"
     restart: always

  markham8-blog:
     depends_on:
       - mysql
     image: wordpress:latest
     ports:
       - "9030:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_DB_NAME: 8thmarkham-blog
     volumes:
       - ../src/markham8-blog/wp-content:/var/www/html/wp-content/

  csc309-tb-exchange:
     depends_on:
       - csc309-mongodb
     image: timothylock/csc309-textbook-exchange:latest
     ports:
       - "9040:80"
     restart: always

  csc309-mongodb:
     image: mongo:latest
     environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
     volumes:
       - ../src/csc309-mongodb/data/db:/data/db
     ports:
       - "9041:27017"
     command: mongod --smallfiles --logpath=/dev/null

  pi-monitor:
     image: timothylock/tim-pi-monitor-demo:latest
     ports:
       - "9050:8880"
     restart: always

  timothy-portfolio:
     image: timothylock/lock-family:latest
     ports:
       - "9060:80"
     restart: always

volumes:
    mysqldata: