apiVersion: v1
kind: Service
metadata:
  name: php-my-admin
spec:
  type: NodePort
  ports:
    - port: 31004
      nodePort: 31004
      targetPort: http
      protocol: TCP
  selector:
    app: php-my-admin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "php-my-admin"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "php-my-admin"
        env: prod
    spec:
      containers:
        - name: php-my-admin
          image: "php-my-admin/php-my-admin:latest"
          ports:
            - containerPort: 80
              name: http
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: PMA_HOST
            value: mysql