homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.6513
  longitude: -79.3756
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml

recorder:
  purge_keep_days: 30
  db_url: !env_var HOME_ASSISTANT_DB_URL

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !env_var HOME_ASSISTANT_API_PASSWORD
  base_url: home.timothylock.ca
  server_port: 8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

switch:
  - platform: tplink
    host: 10.88.111.2
  - platform: tplink
    host: 10.88.111.14
  - platform: rest
    name: Blinds
    resource: http://10.88.111.13:5000/state
    body_on: '{"active": "true"}'
    body_off: '{"active": "false"}'
    is_on_template: '{{ value_json.is_active }}'
    headers:
      Content-Type: application/json

wemo:

camera:
  - platform: generic
    name: Weather
    still_image_url: https://www.yr.no/place/Canada/Ontario/Toronto/meteogram.svg
    content_type: 'image/svg+xml'

tradfri:
  host: 10.88.111.2

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
