recorder:
  purge_keep_days: 30
  db_url: !env_var HOME_ASSISTANT_DB_URL

http:
  base_url: home.timothylock.ca
  server_port: 8123

default_config:

tts:
  - platform: google_translate

switch:
  - platform: rest
    name: Blinds
    resource: http://10.88.111.21:5000/state
    body_on: '{"active": "true"}'
    body_off: '{"active": "false"}'
    is_on_template: '{{ value_json.is_active }}'
    headers:
      Content-Type: application/json
  - platform: rest
    name: Unlock Buzzer For 30 Min
    resource: http://127.0.0.1:10050/buzzer/state
    body_on: '{"active": "true"}'
    body_off: '{"active": "false"}'
    is_on_template: '{{ value_json.is_active }}'
    headers:
      Content-Type: application/json

binary_sensor:
  - platform: ping
    name: Timothys iPhone
    host: 10.88.111.245
    scan_interval: 5
  - platform: ping
    name: Jasons A50
    host: 10.88.111.246
    scan_interval: 5

#device_tracker:
#  - platform: ping
#    interval_seconds: 5
#    hosts:
#      timothyiphone: 10.88.111.245
#      jasonsamsung: 10.88.111.246

#rest_command:
#  turn_off_pc:
#    url: http://10.88.111.32:9001

wemo:

tplink:

automation: !include automations.yaml
